CFLAGS=-Wall -g

all: ex19 spaceWars

ex19: mechanics.o object.o

spaceWars: mechanics.o object.o

clean:
	rm -f spaceWars
	rm -f ex19
	rm -f object.o
	rm -f mechanics.o

test:
	./runTests


